version : '3.8'

services:
  postgres:
    image: postgres:13
    container_name: bentala-postgres
    environment:
      POSTGRES_USER: bentala
      POSTGRES_PASSWORD: bentala
      POSTGRES_DB: bentala
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bentala-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: bentala
      RABBITMQ_DEFAULT_PASS: bentala

volumes:
    postgres-data:
